In [83]:
import pandas as pd
from funciones_manejo_datos import *

In [84]:
df = cargar_archivo('PortoPortugal_50.csv', 'csv')

In [85]:
# Mostrar el DataFrame original
print("DataFrame Original:")
print(df.head())

DataFrame Original:
   Unnamed: 0         id     scrape_id last_scraped       source   host_id  \
0           0   208147.0  2.020000e+13     15/12/24  city scrape   1024383
1           1   241573.0  2.020000e+13     15/12/24  city scrape   1266562
2           2  3902889.0  2.020000e+13     15/12/24  city scrape   4656501
3           3  3907554.0  2.020000e+13     15/12/24  city scrape   3367367
4           4  7918261.0  2.020000e+13     15/12/24  city scrape  40592098

  host_since host_response_time host_response_rate host_acceptance_rate  ...  \
0   26/08/11     within an hour               100%                 100%  ...
1   09/10/11     within an hour               100%                 100%  ...
2   10/01/13     within an hour               100%                 100%  ...
3   25/08/12     within an hour               100%                 100%  ...
4   05/08/15     within an hour               100%                  69%  ...

  review_scores_communication  review_scores_location review_scores_value  \
0                        4.97                    4.84                4.98
1                        4.70                    4.61                4.61
2                        4.69                    4.64                4.58
3                        4.95                    4.62                4.82
4                        4.45                    4.27                4.55

     license instant_bookable  calculated_host_listings_count  \
0     Exempt                t                               1
1    7235/AL                t                              17
2  133235/AL                t                               4
3  69835/AL.                t                               1
4        NaN                f                              24

   calculated_host_listings_count_entire_homes  \
0                                            0
1                                           17
2                                            4
3                                            0
4                                           23

  calculated_host_listings_count_private_rooms  \
0                                            1
1                                            0
2                                            0
3                                            1
4                                            1

  calculated_host_listings_count_shared_rooms  reviews_per_month
0                                           0               0.53
1                                           0               1.40
2                                           0               0.29
3                                           0               2.40
4                                           0               0.10

[5 rows x 51 columns]

In [86]:
nulos_por_columna, total_nulos = identificar_nulos(df)
print("Nulos por columna:")
print(nulos_por_columna)
print("\nTotal de nulos en el dataframe:", total_nulos)

Nulos por columna:
Unnamed: 0                                         0
id                                                 0
scrape_id                                          0
last_scraped                                       0
source                                             0
host_id                                            0
host_since                                         0
host_response_time                              2461
host_response_rate                              2461
host_acceptance_rate                            1696
host_is_superhost                                582
host_listings_count                                0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                       1753
bathrooms_text                                    17
bedrooms                                         492
beds                                            1764
amenities                                          0
price                                           1754
minimum_nights                                     0
maximum_nights                                     0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
first_review                                    1548
last_review                                     1548
review_scores_rating                            1548
review_scores_accuracy                          1549
review_scores_cleanliness                       1549
review_scores_checkin                           1549
review_scores_communication                     1549
review_scores_location                          1549
review_scores_value                             1550
license                                          673
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1548
dtype: int64

Total de nulos en el dataframe: 29140

In [87]:
# Sustituir nulos con ffill
df_ffill = sustituir_nulos_ffill(df)
print("\nDataFrame despu√©s de sustituir nulos con ffill:")
print(df_ffill.head())

DataFrame despu√©s de sustituir nulos con ffill:
   Unnamed: 0         id     scrape_id last_scraped       source   host_id  \
0           0   208147.0  2.020000e+13     15/12/24  city scrape   1024383
1           1   241573.0  2.020000e+13     15/12/24  city scrape   1266562
2           2  3902889.0  2.020000e+13     15/12/24  city scrape   4656501
3           3  3907554.0  2.020000e+13     15/12/24  city scrape   3367367
4           4  7918261.0  2.020000e+13     15/12/24  city scrape  40592098

  host_since host_response_time host_response_rate host_acceptance_rate  ...  \
0   26/08/11     within an hour               100%                 100%  ...
1   09/10/11     within an hour               100%                 100%  ...
2   10/01/13     within an hour               100%                 100%  ...
3   25/08/12     within an hour               100%                 100%  ...
4   05/08/15     within an hour               100%                  69%  ...

  review_scores_communication  review_scores_location review_scores_value  \
0                        4.97                    4.84                4.98
1                        4.70                    4.61                4.61
2                        4.69                    4.64                4.58
3                        4.95                    4.62                4.82
4                        4.45                    4.27                4.55

     license instant_bookable  calculated_host_listings_count  \
0     Exempt                t                               1
1    7235/AL                t                              17
2  133235/AL                t                               4
3  69835/AL.                t                               1
4  69835/AL.                f                              24

   calculated_host_listings_count_entire_homes  \
0                                            0
1                                           17
2                                            4
3                                            0
4                                           23

  calculated_host_listings_count_private_rooms  \
0                                            1
1                                            0
2                                            0
3                                            1
4                                            1

  calculated_host_listings_count_shared_rooms  reviews_per_month
0                                           0               0.53
1                                           0               1.40
2                                           0               0.29
3                                           0               2.40
4                                           0               0.10

[5 rows x 51 columns]

/Users/sergiogiles/Documents/Tec de Monterrey/ConcentracioÃÅn/AnaliÃÅtica de datos y herramientas de inteligencia artificial I/Prof. Alfredo GarciÃÅa/Carga de Datos/funciones_manejo_datos.py:37: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  return df.fillna(method='ffill')

In [88]:
# Sustituir nulos con bfill
df_bfill = sustituir_nulos_bfill(df)
print("\nDataFrame despu√©s de sustituir nulos con bfill:")
print(df_bfill.head())

DataFrame despu√©s de sustituir nulos con bfill:
   Unnamed: 0         id     scrape_id last_scraped       source   host_id  \
0           0   208147.0  2.020000e+13     15/12/24  city scrape   1024383
1           1   241573.0  2.020000e+13     15/12/24  city scrape   1266562
2           2  3902889.0  2.020000e+13     15/12/24  city scrape   4656501
3           3  3907554.0  2.020000e+13     15/12/24  city scrape   3367367
4           4  7918261.0  2.020000e+13     15/12/24  city scrape  40592098

  host_since host_response_time host_response_rate host_acceptance_rate  ...  \
0   26/08/11     within an hour               100%                 100%  ...
1   09/10/11     within an hour               100%                 100%  ...
2   10/01/13     within an hour               100%                 100%  ...
3   25/08/12     within an hour               100%                 100%  ...
4   05/08/15     within an hour               100%                  69%  ...

  review_scores_communication  review_scores_location review_scores_value  \
0                        4.97                    4.84                4.98
1                        4.70                    4.61                4.61
2                        4.69                    4.64                4.58
3                        4.95                    4.62                4.82
4                        4.45                    4.27                4.55

     license instant_bookable  calculated_host_listings_count  \
0     Exempt                t                               1
1    7235/AL                t                              17
2  133235/AL                t                               4
3  69835/AL.                t                               1
4   31917/AL                f                              24

   calculated_host_listings_count_entire_homes  \
0                                            0
1                                           17
2                                            4
3                                            0
4                                           23

  calculated_host_listings_count_private_rooms  \
0                                            1
1                                            0
2                                            0
3                                            1
4                                            1

  calculated_host_listings_count_shared_rooms  reviews_per_month
0                                           0               0.53
1                                           0               1.40
2                                           0               0.29
3                                           0               2.40
4                                           0               0.10

[5 rows x 51 columns]

/Users/sergiogiles/Documents/Tec de Monterrey/ConcentracioÃÅn/AnaliÃÅtica de datos y herramientas de inteligencia artificial I/Prof. Alfredo GarciÃÅa/Carga de Datos/funciones_manejo_datos.py:50: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  return df.fillna(method='bfill')

In [89]:
# Sustituir nulos con un string concreto
df_string = sustituir_nulos_string(df, "Desconocido")
print("\nDataFrame despu√©s de sustituir nulos con 'Desconocido':")
print(df_string.head())

DataFrame despu√©s de sustituir nulos con 'Desconocido':
   Unnamed: 0         id     scrape_id last_scraped       source   host_id  \
0           0   208147.0  2.020000e+13     15/12/24  city scrape   1024383
1           1   241573.0  2.020000e+13     15/12/24  city scrape   1266562
2           2  3902889.0  2.020000e+13     15/12/24  city scrape   4656501
3           3  3907554.0  2.020000e+13     15/12/24  city scrape   3367367
4           4  7918261.0  2.020000e+13     15/12/24  city scrape  40592098

  host_since host_response_time host_response_rate host_acceptance_rate  ...  \
0   26/08/11     within an hour               100%                 100%  ...
1   09/10/11     within an hour               100%                 100%  ...
2   10/01/13     within an hour               100%                 100%  ...
3   25/08/12     within an hour               100%                 100%  ...
4   05/08/15     within an hour               100%                  69%  ...

  review_scores_communication  review_scores_location review_scores_value  \
0                        4.97                    4.84                4.98
1                         4.7                    4.61                4.61
2                        4.69                    4.64                4.58
3                        4.95                    4.62                4.82
4                        4.45                    4.27                4.55

       license instant_bookable  calculated_host_listings_count  \
0       Exempt                t                               1
1      7235/AL                t                              17
2    133235/AL                t                               4
3    69835/AL.                t                               1
4  Desconocido                f                              24

   calculated_host_listings_count_entire_homes  \
0                                            0
1                                           17
2                                            4
3                                            0
4                                           23

  calculated_host_listings_count_private_rooms  \
0                                            1
1                                            0
2                                            0
3                                            1
4                                            1

  calculated_host_listings_count_shared_rooms  reviews_per_month
0                                           0               0.53
1                                           0                1.4
2                                           0               0.29
3                                           0                2.4
4                                           0                0.1

[5 rows x 51 columns]

In [91]:
# Sustituir nulos con el promedio

def sustituir_nulos_promedio(df):
    
    # Seleccionar solo las columnas num√©ricas
    numeric_cols = df.select_dtypes(include=['number']).columns
    
    # Sustituir nulos con el promedio solo en columnas num√©ricas
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())
    
    return df

In [93]:
# Sustituir nulos con el promedio

df_promedio = sustituir_nulos_promedio(df)
print("\nDataFrame despu√©s de sustituir nulos con el promedio:")
print(df_promedio.head())

DataFrame despu√©s de sustituir nulos con el promedio:
   Unnamed: 0         id     scrape_id last_scraped       source   host_id  \
0           0   208147.0  2.020000e+13     15/12/24  city scrape   1024383
1           1   241573.0  2.020000e+13     15/12/24  city scrape   1266562
2           2  3902889.0  2.020000e+13     15/12/24  city scrape   4656501
3           3  3907554.0  2.020000e+13     15/12/24  city scrape   3367367
4           4  7918261.0  2.020000e+13     15/12/24  city scrape  40592098

  host_since host_response_time host_response_rate host_acceptance_rate  ...  \
0   26/08/11     within an hour               100%                 100%  ...
1   09/10/11     within an hour               100%                 100%  ...
2   10/01/13     within an hour               100%                 100%  ...
3   25/08/12     within an hour               100%                 100%  ...
4   05/08/15     within an hour               100%                  69%  ...

  review_scores_communication  review_scores_location review_scores_value  \
0                        4.97                    4.84                4.98
1                        4.70                    4.61                4.61
2                        4.69                    4.64                4.58
3                        4.95                    4.62                4.82
4                        4.45                    4.27                4.55

     license instant_bookable  calculated_host_listings_count  \
0     Exempt                t                               1
1    7235/AL                t                              17
2  133235/AL                t                               4
3  69835/AL.                t                               1
4        NaN                f                              24

   calculated_host_listings_count_entire_homes  \
0                                            0
1                                           17
2                                            4
3                                            0
4                                           23

  calculated_host_listings_count_private_rooms  \
0                                            1
1                                            0
2                                            0
3                                            1
4                                            1

  calculated_host_listings_count_shared_rooms  reviews_per_month
0                                           0               0.53
1                                           0               1.40
2                                           0               0.29
3                                           0               2.40
4                                           0               0.10

[5 rows x 51 columns]

In [94]:
# Sustituir nulos con la mediana

def sustituir_nulos_mediana(df):
    
    # Seleccionar solo las columnas num√©ricas
    numeric_cols = df.select_dtypes(include=['number']).columns
    
    # Sustituir nulos con la mediana solo en columnas num√©ricas
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())
    
    return df

In [95]:
# Sustituir nulos con la mediana
df_mediana = sustituir_nulos_mediana(df)
print("\nDataFrame despu√©s de sustituir nulos con la mediana:")
print(df_mediana.head())

DataFrame despu√©s de sustituir nulos con la mediana:
   Unnamed: 0         id     scrape_id last_scraped       source   host_id  \
0           0   208147.0  2.020000e+13     15/12/24  city scrape   1024383
1           1   241573.0  2.020000e+13     15/12/24  city scrape   1266562
2           2  3902889.0  2.020000e+13     15/12/24  city scrape   4656501
3           3  3907554.0  2.020000e+13     15/12/24  city scrape   3367367
4           4  7918261.0  2.020000e+13     15/12/24  city scrape  40592098

  host_since host_response_time host_response_rate host_acceptance_rate  ...  \
0   26/08/11     within an hour               100%                 100%  ...
1   09/10/11     within an hour               100%                 100%  ...
2   10/01/13     within an hour               100%                 100%  ...
3   25/08/12     within an hour               100%                 100%  ...
4   05/08/15     within an hour               100%                  69%  ...

  review_scores_communication  review_scores_location review_scores_value  \
0                        4.97                    4.84                4.98
1                        4.70                    4.61                4.61
2                        4.69                    4.64                4.58
3                        4.95                    4.62                4.82
4                        4.45                    4.27                4.55

     license instant_bookable  calculated_host_listings_count  \
0     Exempt                t                               1
1    7235/AL                t                              17
2  133235/AL                t                               4
3  69835/AL.                t                               1
4        NaN                f                              24

   calculated_host_listings_count_entire_homes  \
0                                            0
1                                           17
2                                            4
3                                            0
4                                           23

  calculated_host_listings_count_private_rooms  \
0                                            1
1                                            0
2                                            0
3                                            1
4                                            1

  calculated_host_listings_count_shared_rooms  reviews_per_month
0                                           0               0.53
1                                           0               1.40
2                                           0               0.29
3                                           0               2.40
4                                           0               0.10

[5 rows x 51 columns]

In [96]:
# Sustituir nulos con una constante
df_constante = sustituir_nulos_constante(df, 0)
print("\nDataFrame despu√©s de sustituir nulos con 0:")
print(df_constante.head())

DataFrame despu√©s de sustituir nulos con 0:
   Unnamed: 0         id     scrape_id last_scraped       source   host_id  \
0           0   208147.0  2.020000e+13     15/12/24  city scrape   1024383
1           1   241573.0  2.020000e+13     15/12/24  city scrape   1266562
2           2  3902889.0  2.020000e+13     15/12/24  city scrape   4656501
3           3  3907554.0  2.020000e+13     15/12/24  city scrape   3367367
4           4  7918261.0  2.020000e+13     15/12/24  city scrape  40592098

  host_since host_response_time host_response_rate host_acceptance_rate  ...  \
0   26/08/11     within an hour               100%                 100%  ...
1   09/10/11     within an hour               100%                 100%  ...
2   10/01/13     within an hour               100%                 100%  ...
3   25/08/12     within an hour               100%                 100%  ...
4   05/08/15     within an hour               100%                  69%  ...

  review_scores_communication  review_scores_location review_scores_value  \
0                        4.97                    4.84                4.98
1                        4.70                    4.61                4.61
2                        4.69                    4.64                4.58
3                        4.95                    4.62                4.82
4                        4.45                    4.27                4.55

     license instant_bookable  calculated_host_listings_count  \
0     Exempt                t                               1
1    7235/AL                t                              17
2  133235/AL                t                               4
3  69835/AL.                t                               1
4          0                f                              24

   calculated_host_listings_count_entire_homes  \
0                                            0
1                                           17
2                                            4
3                                            0
4                                           23

  calculated_host_listings_count_private_rooms  \
0                                            1
1                                            0
2                                            0
3                                            1
4                                            1

  calculated_host_listings_count_shared_rooms  reviews_per_month
0                                           0               0.53
1                                           0               1.40
2                                           0               0.29
3                                           0               2.40
4                                           0               0.10

[5 rows x 51 columns]

In [57]:
nulos_por_columna = df.isnull().sum()
print(nulos_por_columna)

Unnamed: 0                                         0
id                                                 0
scrape_id                                          0
last_scraped                                       0
source                                             0
host_id                                            0
host_since                                         0
host_response_time                              2461
host_response_rate                              2461
host_acceptance_rate                            1696
host_is_superhost                                582
host_listings_count                                0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                    17
bedrooms                                           0
beds                                               0
amenities                                          0
price                                           1754
minimum_nights                                     0
maximum_nights                                     0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
first_review                                    1548
last_review                                     1548
review_scores_rating                               0
review_scores_accuracy                             0
review_scores_cleanliness                          0
review_scores_checkin                              0
review_scores_communication                        0
review_scores_location                             0
review_scores_value                                0
license                                          673
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                                  0
dtype: int64

In [97]:
df.to_csv('PortoPortugal_50_with_nulls.csv', index=False)